//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunDistribute.DistributeReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistributeReference.IDistributeService")]
    public interface IDistributeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeService/GetValue", ReplyAction="http://tempuri.org/IDistributeService/GetValueResponse")]
        string GetValue(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeService/GetValue", ReplyAction="http://tempuri.org/IDistributeService/GetValueResponse")]
        System.Threading.Tasks.Task<string> GetValueAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDistributeServiceChannel : RunDistribute.DistributeReference.IDistributeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistributeServiceClient : System.ServiceModel.ClientBase<RunDistribute.DistributeReference.IDistributeService>, RunDistribute.DistributeReference.IDistributeService {
        
        public DistributeServiceClient() {
        }
        
        public DistributeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistributeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetValue(int value) {
            return base.Channel.GetValue(value);
        }
        
        public System.Threading.Tasks.Task<string> GetValueAsync(int value) {
            return base.Channel.GetValueAsync(value);
        }
    }
}
